spring:
  datasource:
    url: jdbc:postgresql://ep-green-flower-ao8w7dm9-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: bisque-rehydrated-illustrious-59650.db.redis.io
      port: 19740
      username: default
      password: ${REDIS_PASSWORD}

server:
  port: ${PORT:8080}
jwt:
  private-key: ${JWT_PRIVATE_KEY}
  public-key: ${JWT_PUBLIC_KEY}
  access-token-expiry: 900000
  refresh-token-expiry: 604800000
